# Generated by Django 5.1.4 on 2024-12-28 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genresmodels',
            name='GenresName',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='moviesmodels',
            name='moviesDescription',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='moviesmodels',
            name='moviesName',
            field=models.CharField(blank=True, max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='mpaaratingsmodels',
            name='MpaaLabel',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
